version: '3.0'

services:

  update_service:
    build: src
    container_name: update_service
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      DATABASE_PORT_OVERRIDE: 5432
      DATABASE_HOST_OVERRIDE: database
      GOB_SHARED_DIR: /app/shared
    volumes:
      - gob-volume:/app/shared

  database:
    image: amsterdam/postgres
    ports:
    - "5406:5432"
    container_name: storage
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: gob
      POSTGRES_USER: gob
    volumes:
    - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

volumes:
  gob-volume:
    external: true


networks:
  default:
    external:
      name: gob-network
