version: '3.0'

services:

  gobupload:
    build: src
    container_name: gobupload
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      DATABASE_PORT_OVERRIDE: 5432
      DATABASE_HOST_OVERRIDE: database
      GOB_SHARED_DIR: /app/shared
      GOBOPTIONS: ${GOBOPTIONS}
      SECURE_SALT: insecure
      SECURE_PASSWORD: insecure
    volumes:
      - gob-volume:/app/shared

volumes:
  gob-volume:
    external: true

networks:
  default:
    external:
      name: gob-network
