"""Add bijpijling field to KOT

Revision ID: 007d476ebeec
Revises: 4a6eb2e3dc18
Create Date: 2019-06-12 13:31:30.550635

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '007d476ebeec'
down_revision = '4a6eb2e3dc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brk_kadastraleobjecten', sa.Column('bijpijling_geometrie', geoalchemy2.types.Geometry(srid=28992), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brk_kadastraleobjecten', 'bijpijling_geometrie')
    # ### end Alembic commands ###
