"""gebieden_begin_eind_geldigheid_datetime

Revision ID: 0ce50938f539
Revises: c8eb0d9596a7
Create Date: 2022-02-02 13:11:25.663682

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ce50938f539'
down_revision = 'c8eb0d9596a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop all (materialized) views, rebuild them after the migration
    # You can't alter a column, on which a view is dependant

    op.execute("""
    CREATE OR REPLACE FUNCTION clear_views() RETURNS VOID
    LANGUAGE plpgsql
    AS
    $$
    DECLARE
        c_views CURSOR FOR
        SELECT * FROM pg_views 
        WHERE schemaname='public' 
            and viewowner NOT IN ('postgres', 'azure_superuser')
            and viewname NOT IN (
            'geography_columns', 'geometry_columns', 'raster_columns', 'raster_overviews'
            );
    BEGIN
        FOR v in c_views LOOP
            EXECUTE 'DROP VIEW IF EXISTS ' || v.viewname || ' CASCADE';
        END LOOP;
    END;
    $$;
    SELECT clear_views();
    """)
    op.execute("""
    CREATE OR REPLACE FUNCTION clear_materialized_views() RETURNS VOID
    LANGUAGE plpgsql
    AS
    $$
    DECLARE
        c_views CURSOR FOR
        SELECT * FROM pg_matviews WHERE schemaname='public' and matviewowner != 'postgres';
    BEGIN
        FOR v in c_views LOOP
            EXECUTE 'DROP MATERIALIZED VIEW IF EXISTS ' || v.matviewname || ' CASCADE';
        END LOOP;
    END;
    $$;
    SELECT clear_materialized_views();
    """)

    op.drop_table('rel_gbd_brt_gbd_ggw__ligt_in_ggwgebied')
    op.drop_table('rel_gbd_wijk_gbd_ggw__ligt_in_ggwgebied')
    op.drop_table('rel_gbd_brt_gbd_ggp__ligt_in_ggpgebied')
    op.alter_column('gebieden_bouwblokken', 'begin_geldigheid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_bouwblokken', 'eind_geldigheid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_buurten', 'begin_geldigheid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_buurten', 'eind_geldigheid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_ggpgebieden', 'begin_geldigheid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_ggpgebieden', 'eind_geldigheid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_ggwgebieden', 'begin_geldigheid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_ggwgebieden', 'eind_geldigheid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_stadsdelen', 'begin_geldigheid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_stadsdelen', 'eind_geldigheid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_wijken', 'begin_geldigheid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_wijken', 'eind_geldigheid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gebieden_wijken', 'eind_geldigheid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_wijken', 'begin_geldigheid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_stadsdelen', 'eind_geldigheid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_stadsdelen', 'begin_geldigheid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_ggwgebieden', 'eind_geldigheid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_ggwgebieden', 'begin_geldigheid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_ggpgebieden', 'eind_geldigheid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_ggpgebieden', 'begin_geldigheid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_buurten', 'eind_geldigheid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_buurten', 'begin_geldigheid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_bouwblokken', 'eind_geldigheid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('gebieden_bouwblokken', 'begin_geldigheid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               autoincrement=False)
    op.create_table('rel_gbd_brt_gbd_ggp__ligt_in_ggpgebied',
    sa.Column('_gobid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('derivation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bronwaarde', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_last_dst_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_last_src_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_tid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dst_id', 'dst_volgnummer'], ['gebieden_ggpgebieden._id', 'gebieden_ggpgebieden.volgnummer'], name='rel_gbd_brt_gbd_ggp__ligt_in_ggpgebied_dfk'),
    sa.ForeignKeyConstraint(['src_id', 'src_volgnummer'], ['gebieden_buurten._id', 'gebieden_buurten.volgnummer'], name='rel_gbd_brt_gbd_ggp__ligt_in_ggpgebied_sfk'),
    sa.PrimaryKeyConstraint('_gobid', name='rel_gbd_brt_gbd_ggp__ligt_in_ggpgebied_pkey'),
    sa.UniqueConstraint('_source_id', name='rel_gbd_brt_gbd_ggp__ligt_in_ggpgebied_uniq'),
    sa.UniqueConstraint('_tid', name='rel_gbd_brt_gbd_ggp__ligt_in_ggpgebied__tid_key')
    )
    op.create_table('rel_gbd_wijk_gbd_ggw__ligt_in_ggwgebied',
    sa.Column('_gobid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('derivation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bronwaarde', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_last_dst_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_last_src_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_tid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dst_id', 'dst_volgnummer'], ['gebieden_ggwgebieden._id', 'gebieden_ggwgebieden.volgnummer'], name='rel_gbd_wijk_gbd_ggw__ligt_in_ggwgebied_dfk'),
    sa.ForeignKeyConstraint(['src_id', 'src_volgnummer'], ['gebieden_wijken._id', 'gebieden_wijken.volgnummer'], name='rel_gbd_wijk_gbd_ggw__ligt_in_ggwgebied_sfk'),
    sa.PrimaryKeyConstraint('_gobid', name='rel_gbd_wijk_gbd_ggw__ligt_in_ggwgebied_pkey'),
    sa.UniqueConstraint('_source_id', name='rel_gbd_wijk_gbd_ggw__ligt_in_ggwgebied_uniq'),
    sa.UniqueConstraint('_tid', name='rel_gbd_wijk_gbd_ggw__ligt_in_ggwgebied__tid_key')
    )
    op.create_table('rel_gbd_brt_gbd_ggw__ligt_in_ggwgebied',
    sa.Column('_gobid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('derivation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bronwaarde', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_last_dst_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_last_src_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_tid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dst_id', 'dst_volgnummer'], ['gebieden_ggwgebieden._id', 'gebieden_ggwgebieden.volgnummer'], name='rel_gbd_brt_gbd_ggw__ligt_in_ggwgebied_dfk'),
    sa.ForeignKeyConstraint(['src_id', 'src_volgnummer'], ['gebieden_buurten._id', 'gebieden_buurten.volgnummer'], name='rel_gbd_brt_gbd_ggw__ligt_in_ggwgebied_sfk'),
    sa.PrimaryKeyConstraint('_gobid', name='rel_gbd_brt_gbd_ggw__ligt_in_ggwgebied_pkey'),
    sa.UniqueConstraint('_source_id', name='rel_gbd_brt_gbd_ggw__ligt_in_ggwgebied_uniq'),
    sa.UniqueConstraint('_tid', name='rel_gbd_brt_gbd_ggw__ligt_in_ggwgebied__tid_key')
    )
    # ### end Alembic commands ###
