"""Rename catalogue/entity to catalog/collection and add _id/volgnummer to events

Revision ID: 11370f4a7fa0
Revises: 7e355e481102
Create Date: 2021-02-15 14:30:25.356838

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11370f4a7fa0'
down_revision = '7e355e481102'
branch_labels = None
depends_on = None


def rename_gob_table(old_table_name, new_table_name):
    op.rename_table(old_table_name, new_table_name)
    op.execute(f'ALTER SEQUENCE {old_table_name}__gobid_seq RENAME TO {new_table_name}__gobid_seq')
    op.execute(f'ALTER TABLE {new_table_name} DROP CONSTRAINT {old_table_name}_pkey CASCADE')
    op.execute(f'ALTER TABLE {new_table_name} DROP CONSTRAINT {old_table_name}__id_volgnummer_key CASCADE')
    op.create_primary_key(f'{new_table_name}_pkey', new_table_name, ['_gobid'])
    op.create_unique_constraint(f'{new_table_name}__id_volgnummer_key', new_table_name, ['_id', 'volgnummer'])


def rename_rel_table(old_table_name, new_table_name):
    op.rename_table(old_table_name, new_table_name)
    op.execute(f'ALTER SEQUENCE {old_table_name}__gobid_seq RENAME TO {new_table_name}__gobid_seq')
    op.execute(f'ALTER TABLE {new_table_name} DROP CONSTRAINT {old_table_name}_pkey CASCADE')
    op.execute(f'ALTER TABLE {new_table_name} DROP CONSTRAINT {old_table_name}_uniq CASCADE')
    op.create_primary_key(f'{new_table_name}_pkey', new_table_name, ['_gobid'])
    op.create_unique_constraint(f'{new_table_name}_uniq', new_table_name, ['_source_id'])


def rename_qa_table(old_table_name, new_table_name):
    op.rename_table(old_table_name, new_table_name)
    op.execute(f'ALTER SEQUENCE {old_table_name}__gobid_seq RENAME TO {new_table_name}__gobid_seq')
    op.execute(f'ALTER TABLE {new_table_name} DROP CONSTRAINT {old_table_name}_pkey CASCADE')
    op.execute(f'ALTER TABLE {new_table_name} DROP CONSTRAINT {old_table_name}_uniq CASCADE')
    op.create_primary_key(f'{new_table_name}_pkey', new_table_name, ['_gobid'])
    op.create_unique_constraint(f'{new_table_name}_uniq', new_table_name, ['_source_id'])


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    test_collections = [
        ('test_catalogue_rel_collapsed_a', 'test_catalog_rel_collapsed_a'),
        ('test_catalogue_rel_collapsed_b', 'test_catalog_rel_collapsed_b'),
        ('test_catalogue_rel_multiple_allowed_dst', 'test_catalog_rel_multiple_allowed_dst'),
        ('test_catalogue_rel_multiple_allowed_multisource_src', 'test_catalog_rel_multiple_allowed_multisource_src'),
        ('test_catalogue_rel_multiple_allowed_src', 'test_catalog_rel_multiple_allowed_src'),
        ('test_catalogue_rel_test_entity_a', 'test_catalog_rel_test_collection_a'),
        ('test_catalogue_rel_test_entity_b', 'test_catalog_rel_test_collection_b'),
        ('test_catalogue_rel_test_entity_c', 'test_catalog_rel_test_collection_c'),
        ('test_catalogue_rel_test_entity_d', 'test_catalog_rel_test_collection_d'),
        ('test_catalogue_secure', 'test_catalog_secure'),
        ('test_catalogue_test_entity', 'test_catalog_test_collection'),
        ('test_catalogue_test_entity_autoid', 'test_catalog_test_collection_autoid'),
        ('test_catalogue_test_entity_autoid_states', 'test_catalog_test_collection_autoid_states'),
        ('test_catalogue_test_entity_ref', 'test_catalog_test_collection_ref'),
    ]

    for old_table_name, new_table_name in test_collections:
        rename_gob_table(old_table_name, new_table_name)

    rel_collections = [
        ('rel_tst_sec_tst_tse_secure_reference', 'rel_tst_sec_tst_tsc_secure_reference'),
        ('rel_tst_tse_tst_ter_manyreference', 'rel_tst_tsc_tst_tcr_manyreference'),
        ('rel_tst_tse_tst_ter_reference', 'rel_tst_tsc_tst_tcr_reference'),
    ]

    for old_table_name, new_table_name in rel_collections:
        rename_rel_table(old_table_name, new_table_name)

    op.rename_table('qa_test_catalogue_rel_collapsed_a', 'qa_test_catalog_rel_collapsed_a')
    op.rename_table('qa_test_catalogue_rel_collapsed_b', 'qa_test_catalog_rel_collapsed_b')
    op.rename_table('qa_test_catalogue_rel_multiple_allowed_dst', 'qa_test_catalog_rel_multiple_allowed_dst')
    op.rename_table('qa_test_catalogue_rel_multiple_allowed_multisource_src', 'qa_test_catalog_rel_multiple_allowed_multisource_src')
    op.rename_table('qa_test_catalogue_rel_multiple_allowed_src', 'qa_test_catalog_rel_multiple_allowed_src')
    op.rename_table('qa_test_catalogue_rel_test_entity_a', 'qa_test_catalog_rel_test_collection_a')
    op.rename_table('qa_test_catalogue_rel_test_entity_b', 'qa_test_catalog_rel_test_collection_b')
    op.rename_table('qa_test_catalogue_rel_test_entity_c', 'qa_test_catalog_rel_test_collection_c')
    op.rename_table('qa_test_catalogue_rel_test_entity_d', 'qa_test_catalog_rel_test_collection_d')
    op.rename_table('qa_test_catalogue_secure', 'qa_test_catalog_secure')
    op.rename_table('qa_test_catalogue_test_entity', 'qa_test_catalog_test_collection')
    op.rename_table('qa_test_catalogue_test_entity_autoid', 'qa_test_catalog_test_collection_autoid')
    op.rename_table('qa_test_catalogue_test_entity_autoid_states', 'qa_test_catalog_test_collection_autoid_states')
    op.rename_table('qa_test_catalogue_test_entity_ref', 'qa_test_catalog_test_collection_ref')

    # Save existing events by renaming events table
    op.execute("""
DROP  TABLE IF EXISTS        events_org CASCADE;
ALTER TABLE events RENAME TO events_org;
""")

    # Create new partitioned events table
    # Primary keys are supported on partitioned tables, foreign keys referencing partitioned tables are not supported.
    op.execute("""
CREATE TABLE public.events (
    eventid         SERIAL    NOT NULL,
    "timestamp"     TIMESTAMP NOT NULL,
    catalog         VARCHAR   NOT NULL,
    collection      VARCHAR   NOT NULL,
    "version"       VARCHAR   NOT NULL,
    "action"        VARCHAR   NOT NULL,
    "_id"           VARCHAR,
    "volgnummer"    INTEGER,
    "source"        VARCHAR   NOT NULL,
    source_id       VARCHAR,
    contents        JSONB     NOT NULL,
    application     VARCHAR   NOT NULL,
    PRIMARY KEY (eventid, catalog, collection, source)
) PARTITION BY LIST (catalog);
""")

    # Create events partitions in a separate schema
    op.execute("""
DROP SCHEMA IF EXISTS events CASCADE;
CREATE SCHEMA         events;
""")

    # Create a function to automatically create partitions and insert new events
    op.execute("""
DROP FUNCTION IF EXISTS insertIntoEvents CASCADE;
CREATE FUNCTION         insertIntoEvents (
    ev RECORD
)
RETURNS VOID
AS
$body$
DECLARE
    schema_name TEXT;
    cat_part    TEXT;
    col_part    TEXT;
    src_part    TEXT;
BEGIN
    -- Construct catalog and collection partition table names
    schema_name := 'events';
    -- catalog partition: event_parts.events_catalog
    cat_part    := schema_name || '.' || ev.catalog;
    -- collection partition:    event_parts.events_catalog_collection
    col_part    := cat_part || '_' || ev.collection;
    -- source partition:    event_parts.events_catalog_collection_source
    src_part    := col_part || '_' || lower(ev.source);
    -- Create catalog partition if not yet exists
    IF to_regclass(cat_part) IS NULL THEN
        -- CREATE TABLE cat_part PARTITION OF events FOR VALUES IN (catalog) PARTITION BY LIST (collection)
        EXECUTE 'CREATE TABLE ' ||
                cat_part ||
                ' PARTITION OF events FOR VALUES IN (' ||
                quote_literal(ev.catalog) ||
                ') PARTITION BY LIST(collection)';
    END IF;
    -- Create collection partition exists if not yet exists
    IF to_regclass(col_part) IS NULL THEN
        -- CREATE TABLE col_part PARTITION OF cat_part FOR VALUES IN (collection) PARTITION BY LIST (source)
        EXECUTE 'CREATE TABLE IF NOT EXISTS ' ||
                col_part ||
                ' PARTITION OF ' || cat_part || ' FOR VALUES in (' ||
                quote_literal(ev.collection) ||
                ') PARTITION BY LIST(source)';
    END IF;
    -- Create source partition exists if not yet exists
    IF to_regclass(src_part) IS NULL THEN
        -- CREATE TABLE src_part PARTITION OF col_part FOR VALUES IN (source)
        EXECUTE 'CREATE TABLE IF NOT EXISTS ' ||
                src_part ||
                ' PARTITION OF ' || col_part || ' FOR VALUES in (' ||
                quote_literal(ev.source) ||
                ')';
    END IF;
    -- Insert event in the corresponding catalog-collection-source partition
    -- INSERT INTO src_part (...) VALUES () RETURNING ()
    EXECUTE 'INSERT INTO ' ||
            src_part || ' ' ||
            '(' || 
            'eventid, ' ||
            '"timestamp", ' ||
            'catalog, ' ||
            'collection, ' ||
            '"version", ' ||
            '"action", ' ||
            '"_id", ' ||
            '"volgnummer", ' ||
            '"source", ' ||
            'source_id, ' ||
            'contents, ' ||
            'application' ||
            ') ' ||
            'VALUES (' ||
            ev.eventid                    || ', ' ||
            quote_literal(ev.timestamp)   || ', ' ||
            quote_literal(ev.catalog)   || ', ' ||
            quote_literal(ev.collection)      || ', ' ||
            quote_literal(ev.version)     || ', ' ||
            quote_literal(ev.action)      || ', ' ||
            quote_literal(ev._id)      || ', ' ||
            quote_literal(ev.volgnummer)      || ', ' ||
            quote_literal(ev.source)      || ', ' ||
            coalesce(quote_literal(ev.source_id), 'NULL') || ', ' ||
            quote_literal(ev.contents)    || ', ' ||
            quote_literal(ev.application) ||
            ') ' ||
            'RETURNING (' ||
            ev.eventid                    || ', ' ||
            quote_literal(ev.timestamp)   || ', ' ||
            quote_literal(ev.catalog)   || ', ' ||
            quote_literal(ev.collection)      || ', ' ||
            quote_literal(ev.version)     || ', ' ||
            quote_literal(ev.action)      || ', ' ||
            quote_literal(ev._id)      || ', ' ||
            quote_literal(ev.volgnummer)      || ', ' ||
            quote_literal(ev.source)      || ', ' ||
            coalesce(quote_literal(ev.source_id), 'NULL') || ', ' ||
            quote_literal(ev.contents)    || ', ' ||
            quote_literal(ev.application) ||
            ')';
END;
$body$ LANGUAGE plpgsql;
""")

    # Call the Insert-into-events-partition function on every insert into the events table
    op.execute("""
DROP RULE IF EXISTS autoCall_insertIntoEvents ON events;
CREATE RULE         autoCall_insertIntoEvents
AS
    ON INSERT
    TO events
    DO INSTEAD (
        SELECT insertIntoEvents(NEW);
    );
""")

    # Insert all events in the new partitioned events table
    op.execute("""
INSERT INTO events (
    "eventid",
    "timestamp",
    "catalog",
    "collection",
    "version",
    "action",
    "_id",
    "volgnummer",
    "source",
    "source_id",
    "contents",
    "application"
) SELECT
    eventid,
    timestamp,
    catalogue,
    entity,
    version,
    action,
    NULL as _id,
    NULL as volgnummer,
    source,
    source_id,
    contents,
    application
FROM events_org;
""")

    # Create indexes

    # Quickly find last eventid
    op.execute("""
DROP INDEX IF EXISTS events_eventid;
CREATE INDEX         events_eventid ON events (eventid);
""")
    # Quickly find last action for a specific entity
    op.execute("""
DROP INDEX IF EXISTS events_action;
CREATE INDEX         events_action  ON events ("action");
""")

    # -- In a separate migration, create a function to transform the current events

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
