"""Remove PND onderzoek attribute

Revision ID: 1dab0529324c
Revises: acb19cec6e46
Create Date: 2020-06-18 08:20:46.997390

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1dab0529324c'
down_revision = 'acb19cec6e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bag_panden', 'aanduiding_in_onderzoek')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bag_panden', sa.Column('aanduiding_in_onderzoek', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
