"""Remove onderzoek attribute from BAG SPS

Revision ID: 31243f87ad52
Revises: 1dab0529324c
Create Date: 2020-06-22 10:59:52.678106

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '31243f87ad52'
down_revision = '1dab0529324c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP VIEW IF EXISTS "bag_standplaatsen_enhanced_uva2"')

    op.drop_column('bag_standplaatsen', 'aanduiding_in_onderzoek')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bag_standplaatsen', sa.Column('aanduiding_in_onderzoek', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
