"""source gebieden stadsdelen from amsterdam schema

Revision ID: 3803c9d97842
Revises: 0778641b0580
Create Date: 2022-08-15 09:34:00.199646

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

from gobupload.alembic_utils import RenamedRelation, upgrade_relations, downgrade_relations

# revision identifiers, used by Alembic.
revision = '3803c9d97842'
down_revision = '0778641b0580'
branch_labels = None
depends_on = None

renamed_relations = [
    RenamedRelation(
        table_name='gebieden_stadsdelen',
        old_column='ligt_in_gemeente',
        new_column='ligt_in_brk_gemeente',
        old_relation_table='rel_gbd_sdl_brk_gme_ligt_in_gemeente',
        new_relation_table='rel_gbd_sdl_brk_gme_ligt_in_brk_gemeente'
    )
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gebieden_stadsdelen', sa.Column('datum_actueel_tot', sa.DateTime(), autoincrement=False, nullable=True))

    upgrade_relations(op, renamed_relations)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gebieden_stadsdelen', 'datum_actueel_tot')

    downgrade_relations(op, renamed_relations)
    # ### end Alembic commands ###
