"""Fix id's and references on BRK for inconsistent data

Revision ID: 3a0eb006caf1
Revises: eea7dd95cb3d
Create Date: 2019-05-14 10:29:52.043708

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a0eb006caf1'
down_revision = 'eea7dd95cb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brk_aantekeningenrechten', sa.Column('id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('brk_kadastraleobjecten', sa.Column('id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('brk_kadastralesubjecten', sa.Column('id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('brk_tenaamstellingen', sa.Column('id', sa.Integer(), autoincrement=False, nullable=True))
    op.drop_column('brk_tenaamstellingen', 'registratiedatum')
    op.add_column('brk_zakelijkerechten', sa.Column('id', sa.Integer(), autoincrement=False, nullable=True))
    op.drop_column('brk_zakelijkerechten', '_nrn_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brk_zakelijkerechten', sa.Column('_nrn_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('brk_zakelijkerechten', 'id')
    op.add_column('brk_tenaamstellingen', sa.Column('registratiedatum', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('brk_tenaamstellingen', 'id')
    op.drop_column('brk_kadastralesubjecten', 'id')
    op.drop_column('brk_kadastraleobjecten', 'id')
    op.drop_column('brk_aantekeningenrechten', 'id')
    # ### end Alembic commands ###
