"""brk2 kadastralesubjecten

Revision ID: 40e46beb1815
Revises: 6ba2e705529d
Create Date: 2022-11-16 11:57:50.360835

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40e46beb1815'
down_revision = '6ba2e705529d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brk2_kadastralesubjecten',
    sa.Column('identificatie', sa.String(), autoincrement=False, nullable=True),
    sa.Column('type_subject', sa.String(), autoincrement=False, nullable=True),
    sa.Column('beschikkingsbevoegdheid', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('indicatie_afscherming_gegevens', sa.String(), autoincrement=False, nullable=True),
    sa.Column('heeft_bsn_voor_brp_persoon', sa.String(), autoincrement=False, nullable=True),
    sa.Column('voornamen', sa.String(), autoincrement=False, nullable=True),
    sa.Column('voorvoegsels', sa.String(), autoincrement=False, nullable=True),
    sa.Column('geslachtsnaam', sa.String(), autoincrement=False, nullable=True),
    sa.Column('geslacht', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('naam_gebruik', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('titel_of_predicaat', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('indicatie_diakriet_niet_toonbaar', sa.String(), autoincrement=False, nullable=True),
    sa.Column('geboortedatum', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('geboortedatum_onvolledig', sa.String(), autoincrement=False, nullable=True),
    sa.Column('geboorteplaats', sa.String(), autoincrement=False, nullable=True),
    sa.Column('geboorteland', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datum_overlijden', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('datum_overlijden_onvolledig', sa.String(), autoincrement=False, nullable=True),
    sa.Column('indicatie_overleden', sa.String(), autoincrement=False, nullable=True),
    sa.Column('voornamen_partner', sa.String(), autoincrement=False, nullable=True),
    sa.Column('voorvoegsels_partner', sa.String(), autoincrement=False, nullable=True),
    sa.Column('geslachtsnaam_partner', sa.String(), autoincrement=False, nullable=True),
    sa.Column('heeft_rsin_voor_hr_niet_natuurlijkepersoon', sa.String(), autoincrement=False, nullable=True),
    sa.Column('heeft_kvknummer_voor_hr_maatschappelijkeactiviteit', sa.String(), autoincrement=False, nullable=True),
    sa.Column('rechtsvorm', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('statutaire_naam', sa.String(), autoincrement=False, nullable=True),
    sa.Column('statutaire_zetel', sa.String(), autoincrement=False, nullable=True),
    sa.Column('woonadres', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('land_waarnaar_vertrokken', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('postadres', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datum_actueel_tot', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('toestandsdatum', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_tid', sa.String(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_gobid'),
    sa.UniqueConstraint('_id', name='brk2_kadastralesubjecten__id_key'),
    sa.UniqueConstraint('_tid', name='brk2_kadastralesubjecten__tid_key')
    )
    op.create_table('qa_brk2_kadastralesubjecten',
    sa.Column('meldingnummer', sa.String(), autoincrement=False, nullable=True),
    sa.Column('code', sa.String(), autoincrement=False, nullable=True),
    sa.Column('proces', sa.String(), autoincrement=False, nullable=True),
    sa.Column('attribuut', sa.String(), autoincrement=False, nullable=True),
    sa.Column('identificatie', sa.String(), autoincrement=False, nullable=True),
    sa.Column('volgnummer', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('betwijfelde_waarde', sa.String(), autoincrement=False, nullable=True),
    sa.Column('onderbouwing', sa.String(), autoincrement=False, nullable=True),
    sa.Column('voorgestelde_waarde', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_tid', sa.String(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_gobid'),
    sa.UniqueConstraint('_id', name='qa_brk2_kadastralesubjecten__id_key'),
    sa.UniqueConstraint('_tid', name='qa_brk2_kadastralesubjecten__tid_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_brk2_kadastralesubjecten')
    op.drop_table('brk2_kadastralesubjecten')
    # ### end Alembic commands ###
