"""ggwggp

Revision ID: 50a4daeb9e88
Revises: d721110eb79c
Create Date: 2019-01-15 15:54:27.048712

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50a4daeb9e88'
down_revision = 'd721110eb79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gebieden_ggpgebieden',
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('volgnummer', sa.String(), autoincrement=False, nullable=True),
    sa.Column('registratiedatum', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('identificatie', sa.String(), autoincrement=False, nullable=True),
    sa.Column('naam', sa.String(), autoincrement=False, nullable=True),
    sa.Column('code', sa.String(), autoincrement=False, nullable=True),
    sa.Column('datum_begin_geldigheid', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('datum_einde_geldigheid', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('documentdatum', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('documentnummer', sa.String(), autoincrement=False, nullable=True),
    sa.Column('ligt_in_stadsdeel', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('bestaat_uit_buurten', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('geometrie', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=28992), nullable=True),
    sa.PrimaryKeyConstraint('_gobid')
    )
    op.create_table('gebieden_ggwgebieden',
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('volgnummer', sa.String(), autoincrement=False, nullable=True),
    sa.Column('registratiedatum', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('identificatie', sa.String(), autoincrement=False, nullable=True),
    sa.Column('naam', sa.String(), autoincrement=False, nullable=True),
    sa.Column('code', sa.String(), autoincrement=False, nullable=True),
    sa.Column('datum_begin_geldigheid', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('datum_einde_geldigheid', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('documentdatum', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('documentnummer', sa.String(), autoincrement=False, nullable=True),
    sa.Column('ligt_in_stadsdeel', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('bestaat_uit_wijken', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('geometrie', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=28992), nullable=True),
    sa.PrimaryKeyConstraint('_gobid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gebieden_ggwgebieden')
    op.drop_table('gebieden_ggpgebieden')
    # ### end Alembic commands ###
