"""remove einddatum from zrt model

Revision ID: 59fa94daa1ea
Revises: 4f34dcc28eb6
Create Date: 2019-09-11 11:12:00.749457

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59fa94daa1ea'
down_revision = '4f34dcc28eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brk_zakelijkerechten', 'einddatum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brk_zakelijkerechten', sa.Column('einddatum', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
