"""update monumenten

Revision ID: 63e5e7e96215
Revises: 097fd62ade0a
Create Date: 2023-12-01 13:31:23.731322

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63e5e7e96215'
down_revision = '097fd62ade0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("DROP VIEW IF EXISTS legacy.monumenten_monumenten CASCADE")
    op.execute("DROP VIEW IF EXISTS legacy.monumenten_complexen CASCADE")
    op.execute("DROP VIEW IF EXISTS legacy.monumenten_situeringen CASCADE")

    op.add_column('monumenten_complexen', sa.Column('naam', sa.String(), autoincrement=False, nullable=True))
    op.add_column('monumenten_complexen', sa.Column('datum_actueel_tot', sa.DateTime(), autoincrement=False, nullable=True))
    op.drop_column('monumenten_complexen', 'complex_naam')
    op.add_column('monumenten_monumenten', sa.Column('monumentnummer', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('adressering', sa.String(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('naam', sa.String(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('datum_aanwijzing', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('datum_afvoeren', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('jaar_begin_van', sa.String(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('jaar_begin_tot', sa.String(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('punt_coordinaten', geoalchemy2.types.Geometry(geometry_type='POINT', srid=28992, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('contour', geoalchemy2.types.Geometry(srid=28992, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('datum_actueel_tot', sa.DateTime(), autoincrement=False, nullable=True))
    op.drop_column('monumenten_monumenten', 'coordinaten')
    op.drop_column('monumenten_monumenten', 'monument_naam')
    op.drop_column('monumenten_monumenten', 'monument_nummer')
    op.drop_column('monumenten_monumenten', 'bouwjaar_eind_bouwperiode')
    op.drop_column('monumenten_monumenten', 'bouwjaar_start_bouwperiode')
    op.drop_column('monumenten_monumenten', 'aanwijzingsdatum')
    op.drop_column('monumenten_monumenten', 'orde_naam')
    op.add_column('monumenten_situeringen', sa.Column('datum_actueel_tot', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('monumenten_unesco', sa.Column('datum_aanwijzing', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('monumenten_unesco', sa.Column('datum_afvoeren', sa.DateTime(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monumenten_unesco', 'datum_afvoeren')
    op.drop_column('monumenten_unesco', 'datum_aanwijzing')
    op.drop_column('monumenten_situeringen', 'datum_actueel_tot')
    op.add_column('monumenten_monumenten', sa.Column('orde_naam', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('aanwijzingsdatum', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('bouwjaar_start_bouwperiode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('bouwjaar_eind_bouwperiode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('monument_nummer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('monument_naam', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('monumenten_monumenten', sa.Column('coordinaten', geoalchemy2.types.Geometry(geometry_type='POINT', srid=28992, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    op.drop_column('monumenten_monumenten', 'datum_actueel_tot')
    op.drop_column('monumenten_monumenten', 'contour')
    op.drop_column('monumenten_monumenten', 'punt_coordinaten')
    op.drop_column('monumenten_monumenten', 'jaar_begin_tot')
    op.drop_column('monumenten_monumenten', 'jaar_begin_van')
    op.drop_column('monumenten_monumenten', 'datum_afvoeren')
    op.drop_column('monumenten_monumenten', 'datum_aanwijzing')
    op.drop_column('monumenten_monumenten', 'naam')
    op.drop_column('monumenten_monumenten', 'adressering')
    op.drop_column('monumenten_monumenten', 'monumentnummer')
    op.add_column('monumenten_complexen', sa.Column('complex_naam', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('monumenten_complexen', 'datum_actueel_tot')
    op.drop_column('monumenten_complexen', 'naam')
    # ### end Alembic commands ###
