"""remove brk art aard_zakelijkrecht

Revision ID: 691b1f840601
Revises: c7150709e009
Create Date: 2019-08-22 15:38:13.582151

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '691b1f840601'
down_revision = 'c7150709e009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brk_aantekeningenrechten', 'aard_zakelijk_recht')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brk_aantekeningenrechten', sa.Column('aard_zakelijk_recht', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
