"""json_test

Revision ID: 73620e7c21ea
Revises: 29149a285ff2
Create Date: 2019-01-21 14:31:16.116994

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73620e7c21ea'
down_revision = '29149a285ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_catalogue_test_entity', sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_catalogue_test_entity', 'json')
    # ### end Alembic commands ###
