"""Remove amsterdamse sleutel

Revision ID: 7e355e481102
Revises: 1f9556cc1398
Create Date: 2021-01-26 16:25:44.089673

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7e355e481102'
down_revision = '1f9556cc1398'
branch_labels = None
depends_on = None


def upgrade():
    # Remove all enhanced for UVA2 views
    op.execute('DROP VIEW IF EXISTS "bag_ligplaatsen_enhanced_uva2"')
    op.execute('DROP VIEW IF EXISTS "bag_standplaatsen_enhanced_uva2"')
    op.execute('DROP VIEW IF EXISTS "bag_verblijfsobjecten_enhanced_uva2"')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bag_ligplaatsen', 'amsterdamse_sleutel')
    op.drop_column('bag_nummeraanduidingen', 'amsterdamse_sleutel')
    op.drop_column('bag_openbareruimtes', 'amsterdamse_sleutel')
    op.drop_column('bag_panden', 'amsterdamse_sleutel')
    op.drop_column('bag_standplaatsen', 'amsterdamse_sleutel')
    op.drop_column('bag_verblijfsobjecten', 'amsterdamse_sleutel')
    op.drop_column('bag_woonplaatsen', 'amsterdamse_sleutel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bag_woonplaatsen', sa.Column('amsterdamse_sleutel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bag_verblijfsobjecten', sa.Column('amsterdamse_sleutel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bag_standplaatsen', sa.Column('amsterdamse_sleutel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bag_panden', sa.Column('amsterdamse_sleutel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bag_openbareruimtes', sa.Column('amsterdamse_sleutel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bag_nummeraanduidingen', sa.Column('amsterdamse_sleutel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bag_ligplaatsen', sa.Column('amsterdamse_sleutel', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
