"""Fix HR Locaties states

Revision ID: 7f9e68845a4b
Revises: 8e60d09c8202
Create Date: 2021-03-17 06:31:33.361847

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7f9e68845a4b'
down_revision = '8e60d09c8202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_locaties', sa.Column('begin_geldigheid', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('hr_locaties', sa.Column('eind_geldigheid', sa.DateTime(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_locaties', 'eind_geldigheid')
    op.drop_column('hr_locaties', 'begin_geldigheid')
    # ### end Alembic commands ###
