"""add_ligt_in_gemeente_gebieden

Revision ID: 8469e1243db6
Revises: d201dcaa792c
Create Date: 2022-04-13 13:43:00.835663

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8469e1243db6'
down_revision = 'd201dcaa792c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rel_gbd_bbk_brk_gme_ligt_in_gemeente',
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('src_source', sa.String(), nullable=True),
    sa.Column('src_id', sa.String(), nullable=True),
    sa.Column('src_volgnummer', sa.Integer(), nullable=True),
    sa.Column('bronwaarde', sa.String(), nullable=True),
    sa.Column('derivation', sa.String(), nullable=True),
    sa.Column('dst_source', sa.String(), nullable=True),
    sa.Column('dst_id', sa.String(), nullable=True),
    sa.Column('dst_volgnummer', sa.Integer(), nullable=True),
    sa.Column('begin_geldigheid', sa.DateTime(), nullable=True),
    sa.Column('eind_geldigheid', sa.DateTime(), nullable=True),
    sa.Column('_last_src_event', sa.Integer(), nullable=True),
    sa.Column('_last_dst_event', sa.Integer(), nullable=True),
    sa.Column('_source', sa.String(), nullable=True),
    sa.Column('_application', sa.String(), nullable=True),
    sa.Column('_source_id', sa.String(), nullable=True),
    sa.Column('_last_event', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(), nullable=True),
    sa.Column('_version', sa.String(), nullable=True),
    sa.Column('_date_created', sa.DateTime(), nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), nullable=True),
    sa.Column('_date_modified', sa.DateTime(), nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), nullable=True),
    sa.Column('_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), nullable=True),
    sa.Column('_tid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dst_id', 'dst_volgnummer'], ['brk_gemeentes._id', 'brk_gemeentes.volgnummer'], name='rel_gbd_bbk_brk_gme_ligt_in_gemeente_dfk'),
    sa.ForeignKeyConstraint(['src_id', 'src_volgnummer'], ['gebieden_bouwblokken._id', 'gebieden_bouwblokken.volgnummer'], name='rel_gbd_bbk_brk_gme_ligt_in_gemeente_sfk'),
    sa.PrimaryKeyConstraint('_gobid'),
    sa.UniqueConstraint('_source_id', name='rel_gbd_bbk_brk_gme_ligt_in_gemeente_uniq'),
    sa.UniqueConstraint('_tid', name='rel_gbd_bbk_brk_gme_ligt_in_gemeente__tid_key')
    )
    op.create_table('rel_gbd_brt_brk_gme_ligt_in_gemeente',
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('src_source', sa.String(), nullable=True),
    sa.Column('src_id', sa.String(), nullable=True),
    sa.Column('src_volgnummer', sa.Integer(), nullable=True),
    sa.Column('bronwaarde', sa.String(), nullable=True),
    sa.Column('derivation', sa.String(), nullable=True),
    sa.Column('dst_source', sa.String(), nullable=True),
    sa.Column('dst_id', sa.String(), nullable=True),
    sa.Column('dst_volgnummer', sa.Integer(), nullable=True),
    sa.Column('begin_geldigheid', sa.DateTime(), nullable=True),
    sa.Column('eind_geldigheid', sa.DateTime(), nullable=True),
    sa.Column('_last_src_event', sa.Integer(), nullable=True),
    sa.Column('_last_dst_event', sa.Integer(), nullable=True),
    sa.Column('_source', sa.String(), nullable=True),
    sa.Column('_application', sa.String(), nullable=True),
    sa.Column('_source_id', sa.String(), nullable=True),
    sa.Column('_last_event', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(), nullable=True),
    sa.Column('_version', sa.String(), nullable=True),
    sa.Column('_date_created', sa.DateTime(), nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), nullable=True),
    sa.Column('_date_modified', sa.DateTime(), nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), nullable=True),
    sa.Column('_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), nullable=True),
    sa.Column('_tid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dst_id', 'dst_volgnummer'], ['brk_gemeentes._id', 'brk_gemeentes.volgnummer'], name='rel_gbd_brt_brk_gme_ligt_in_gemeente_dfk'),
    sa.ForeignKeyConstraint(['src_id', 'src_volgnummer'], ['gebieden_buurten._id', 'gebieden_buurten.volgnummer'], name='rel_gbd_brt_brk_gme_ligt_in_gemeente_sfk'),
    sa.PrimaryKeyConstraint('_gobid'),
    sa.UniqueConstraint('_source_id', name='rel_gbd_brt_brk_gme_ligt_in_gemeente_uniq'),
    sa.UniqueConstraint('_tid', name='rel_gbd_brt_brk_gme_ligt_in_gemeente__tid_key')
    )
    op.create_table('rel_gbd_ggp_brk_gme_ligt_in_gemeente',
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('src_source', sa.String(), nullable=True),
    sa.Column('src_id', sa.String(), nullable=True),
    sa.Column('src_volgnummer', sa.Integer(), nullable=True),
    sa.Column('bronwaarde', sa.String(), nullable=True),
    sa.Column('derivation', sa.String(), nullable=True),
    sa.Column('dst_source', sa.String(), nullable=True),
    sa.Column('dst_id', sa.String(), nullable=True),
    sa.Column('dst_volgnummer', sa.Integer(), nullable=True),
    sa.Column('begin_geldigheid', sa.DateTime(), nullable=True),
    sa.Column('eind_geldigheid', sa.DateTime(), nullable=True),
    sa.Column('_last_src_event', sa.Integer(), nullable=True),
    sa.Column('_last_dst_event', sa.Integer(), nullable=True),
    sa.Column('_source', sa.String(), nullable=True),
    sa.Column('_application', sa.String(), nullable=True),
    sa.Column('_source_id', sa.String(), nullable=True),
    sa.Column('_last_event', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(), nullable=True),
    sa.Column('_version', sa.String(), nullable=True),
    sa.Column('_date_created', sa.DateTime(), nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), nullable=True),
    sa.Column('_date_modified', sa.DateTime(), nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), nullable=True),
    sa.Column('_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), nullable=True),
    sa.Column('_tid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dst_id', 'dst_volgnummer'], ['brk_gemeentes._id', 'brk_gemeentes.volgnummer'], name='rel_gbd_ggp_brk_gme_ligt_in_gemeente_dfk'),
    sa.ForeignKeyConstraint(['src_id', 'src_volgnummer'], ['gebieden_ggpgebieden._id', 'gebieden_ggpgebieden.volgnummer'], name='rel_gbd_ggp_brk_gme_ligt_in_gemeente_sfk'),
    sa.PrimaryKeyConstraint('_gobid'),
    sa.UniqueConstraint('_source_id', name='rel_gbd_ggp_brk_gme_ligt_in_gemeente_uniq'),
    sa.UniqueConstraint('_tid', name='rel_gbd_ggp_brk_gme_ligt_in_gemeente__tid_key')
    )
    op.create_table('rel_gbd_ggw_brk_gme_ligt_in_gemeente',
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('src_source', sa.String(), nullable=True),
    sa.Column('src_id', sa.String(), nullable=True),
    sa.Column('src_volgnummer', sa.Integer(), nullable=True),
    sa.Column('bronwaarde', sa.String(), nullable=True),
    sa.Column('derivation', sa.String(), nullable=True),
    sa.Column('dst_source', sa.String(), nullable=True),
    sa.Column('dst_id', sa.String(), nullable=True),
    sa.Column('dst_volgnummer', sa.Integer(), nullable=True),
    sa.Column('begin_geldigheid', sa.DateTime(), nullable=True),
    sa.Column('eind_geldigheid', sa.DateTime(), nullable=True),
    sa.Column('_last_src_event', sa.Integer(), nullable=True),
    sa.Column('_last_dst_event', sa.Integer(), nullable=True),
    sa.Column('_source', sa.String(), nullable=True),
    sa.Column('_application', sa.String(), nullable=True),
    sa.Column('_source_id', sa.String(), nullable=True),
    sa.Column('_last_event', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(), nullable=True),
    sa.Column('_version', sa.String(), nullable=True),
    sa.Column('_date_created', sa.DateTime(), nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), nullable=True),
    sa.Column('_date_modified', sa.DateTime(), nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), nullable=True),
    sa.Column('_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), nullable=True),
    sa.Column('_tid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dst_id', 'dst_volgnummer'], ['brk_gemeentes._id', 'brk_gemeentes.volgnummer'], name='rel_gbd_ggw_brk_gme_ligt_in_gemeente_dfk'),
    sa.ForeignKeyConstraint(['src_id', 'src_volgnummer'], ['gebieden_ggwgebieden._id', 'gebieden_ggwgebieden.volgnummer'], name='rel_gbd_ggw_brk_gme_ligt_in_gemeente_sfk'),
    sa.PrimaryKeyConstraint('_gobid'),
    sa.UniqueConstraint('_source_id', name='rel_gbd_ggw_brk_gme_ligt_in_gemeente_uniq'),
    sa.UniqueConstraint('_tid', name='rel_gbd_ggw_brk_gme_ligt_in_gemeente__tid_key')
    )
    op.create_table('rel_gbd_wijk_brk_gme_ligt_in_gemeente',
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('src_source', sa.String(), nullable=True),
    sa.Column('src_id', sa.String(), nullable=True),
    sa.Column('src_volgnummer', sa.Integer(), nullable=True),
    sa.Column('bronwaarde', sa.String(), nullable=True),
    sa.Column('derivation', sa.String(), nullable=True),
    sa.Column('dst_source', sa.String(), nullable=True),
    sa.Column('dst_id', sa.String(), nullable=True),
    sa.Column('dst_volgnummer', sa.Integer(), nullable=True),
    sa.Column('begin_geldigheid', sa.DateTime(), nullable=True),
    sa.Column('eind_geldigheid', sa.DateTime(), nullable=True),
    sa.Column('_last_src_event', sa.Integer(), nullable=True),
    sa.Column('_last_dst_event', sa.Integer(), nullable=True),
    sa.Column('_source', sa.String(), nullable=True),
    sa.Column('_application', sa.String(), nullable=True),
    sa.Column('_source_id', sa.String(), nullable=True),
    sa.Column('_last_event', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(), nullable=True),
    sa.Column('_version', sa.String(), nullable=True),
    sa.Column('_date_created', sa.DateTime(), nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), nullable=True),
    sa.Column('_date_modified', sa.DateTime(), nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), nullable=True),
    sa.Column('_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), nullable=True),
    sa.Column('_tid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dst_id', 'dst_volgnummer'], ['brk_gemeentes._id', 'brk_gemeentes.volgnummer'], name='rel_gbd_wijk_brk_gme_ligt_in_gemeente_dfk'),
    sa.ForeignKeyConstraint(['src_id', 'src_volgnummer'], ['gebieden_wijken._id', 'gebieden_wijken.volgnummer'], name='rel_gbd_wijk_brk_gme_ligt_in_gemeente_sfk'),
    sa.PrimaryKeyConstraint('_gobid'),
    sa.UniqueConstraint('_source_id', name='rel_gbd_wijk_brk_gme_ligt_in_gemeente_uniq'),
    sa.UniqueConstraint('_tid', name='rel_gbd_wijk_brk_gme_ligt_in_gemeente__tid_key')
    )
    op.add_column('gebieden_bouwblokken', sa.Column('ligt_in_gemeente', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('gebieden_buurten', sa.Column('ligt_in_gemeente', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('gebieden_ggpgebieden', sa.Column('ligt_in_gemeente', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('gebieden_ggwgebieden', sa.Column('ligt_in_gemeente', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('gebieden_wijken', sa.Column('ligt_in_gemeente', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gebieden_wijken', 'ligt_in_gemeente')
    op.drop_column('gebieden_ggwgebieden', 'ligt_in_gemeente')
    op.drop_column('gebieden_ggpgebieden', 'ligt_in_gemeente')
    op.drop_column('gebieden_buurten', 'ligt_in_gemeente')
    op.drop_column('gebieden_bouwblokken', 'ligt_in_gemeente')

    op.drop_table('rel_gbd_wijk_brk_gme_ligt_in_gemeente')
    op.drop_table('rel_gbd_ggw_brk_gme_ligt_in_gemeente')
    op.drop_table('rel_gbd_ggp_brk_gme_ligt_in_gemeente')
    op.drop_table('rel_gbd_brt_brk_gme_ligt_in_gemeente')
    op.drop_table('rel_gbd_bbk_brk_gme_ligt_in_gemeente')
    # ### end Alembic commands ###
