"""recreate_hr_tables_incomplete_date

Revision ID: 8932b78962c2
Revises: 9681961b1b9c
Create Date: 2021-05-12 11:01:16.282834

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8932b78962c2'
down_revision = '9681961b1b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE hr_locaties CASCADE')
    op.alter_column('hr_locaties', 'datum_aanvang', type_=postgresql.JSONB, postgresql_using='datum_aanvang::text::jsonb')
    op.alter_column('hr_locaties', 'datum_einde', type_=postgresql.JSONB, postgresql_using='datum_einde::text::jsonb')

    op.execute('TRUNCATE TABLE hr_vestigingen CASCADE')
    op.alter_column('hr_vestigingen', 'datum_aanvang', type_=postgresql.JSONB, postgresql_using='datum_aanvang::text::jsonb')
    op.alter_column('hr_vestigingen', 'datum_einde', type_=postgresql.JSONB, postgresql_using='datum_einde::text::jsonb')
    op.alter_column('hr_vestigingen', 'datum_voortzetting', type_=postgresql.JSONB, postgresql_using='datum_voortzetting::text::jsonb')

    op.execute('TRUNCATE TABLE hr_maatschappelijkeactiviteiten CASCADE')
    op.alter_column('hr_maatschappelijkeactiviteiten', 'datum_aanvang_onderneming', type_=postgresql.JSONB, postgresql_using='datum_aanvang_onderneming::text::jsonb')
    op.alter_column('hr_maatschappelijkeactiviteiten', 'datum_einde_onderneming', type_=postgresql.JSONB, postgresql_using='datum_einde_onderneming::text::jsonb')
    op.alter_column('hr_maatschappelijkeactiviteiten', 'datum_overdracht_voortzetting_onderneming', type_=postgresql.JSONB, postgresql_using='datum_overdracht_voortzetting_onderneming::text::jsonb')
    op.alter_column('hr_maatschappelijkeactiviteiten', 'datum_aanvang_maatschappelijke_activiteit', type_=postgresql.JSONB, postgresql_using='datum_aanvang_maatschappelijke_activiteit::text::jsonb')
    op.alter_column('hr_maatschappelijkeactiviteiten', 'datum_einde_maatschappelijke_activiteit', type_=postgresql.JSONB, postgresql_using='datum_einde_maatschappelijke_activiteit::text::jsonb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE hr_locaties CASCADE')
    op.alter_column('hr_locaties', 'datum_aanvang', type_=postgresql.DATE, postgresql_using='datum_aanvang::text::date')
    op.alter_column('hr_locaties', 'datum_einde', type_=postgresql.DATE, postgresql_using='datum_einde::text::date')

    op.execute('TRUNCATE TABLE hr_vestigingen CASCADE')
    op.alter_column('hr_vestigingen', 'datum_aanvang', type_=postgresql.DATE, postgresql_using='datum_aanvang::text::date')
    op.alter_column('hr_vestigingen', 'datum_einde', type_=postgresql.DATE, postgresql_using='datum_einde::text::date')
    op.alter_column('hr_vestigingen', 'datum_voortzetting', type_=postgresql.DATE, postgresql_using='datum_voortzetting::text::date')

    op.execute('TRUNCATE TABLE hr_maatschappelijkeactiviteiten CASCADE')
    op.alter_column('hr_maatschappelijkeactiviteiten', 'datum_aanvang_onderneming', type_=postgresql.DATE, postgresql_using='datum_aanvang_onderneming::text::date')
    op.alter_column('hr_maatschappelijkeactiviteiten', 'datum_einde_onderneming', type_=postgresql.DATE, postgresql_using='datum_einde_onderneming::text::date')
    op.alter_column('hr_maatschappelijkeactiviteiten', 'datum_overdracht_voortzetting_onderneming', type_=postgresql.DATE, postgresql_using='datum_overdracht_voortzetting_onderneming::text::date')
    op.alter_column('hr_maatschappelijkeactiviteiten', 'datum_aanvang_maatschappelijke_activiteit', type_=postgresql.DATE, postgresql_using='datum_aanvang_maatschappelijke_activiteit::text::date')
    op.alter_column('hr_maatschappelijkeactiviteiten', 'datum_einde_maatschappelijke_activiteit', type_=postgresql.DATE, postgresql_using='datum_einde_maatschappelijke_activiteit::text::date')
    # ### end Alembic commands ###
