"""BGT Overbouw

Revision ID: 92d508efb84f
Revises: 3d1d3ba6873a
Create Date: 2019-10-04 09:28:22.539060

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92d508efb84f'
down_revision = '3d1d3ba6873a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bgt_overbouw',
    sa.Column('volgnummer', sa.String(), autoincrement=False, nullable=True),
    sa.Column('registratiedatum', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('identificatie', sa.String(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('relatieve_hoogteligging', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('geometrie', geoalchemy2.types.Geometry(srid=28992), nullable=True),
    sa.Column('_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_gobid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bgt_overbouw')
    # ### end Alembic commands ###
