"""source gebieden buurten from amsterdam schema

Revision ID: 9fc091ab554d
Revises: 94622e8d6a47
Create Date: 2022-08-15 08:25:27.028365

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from gobupload.alembic_utils import RenamedRelation, downgrade_relations, upgrade_relations

revision = '9fc091ab554d'
down_revision = '94622e8d6a47'
branch_labels = None
depends_on = None


renamed_relations = [
    RenamedRelation(
        table_name="gebieden_buurten",
        old_column="ligt_in_gemeente",
        new_column="ligt_in_brk_gemeente",
        old_relation_table="rel_gbd_brt_brk_gme_ligt_in_gemeente",
        new_relation_table="rel_gbd_brt_brk_gme_ligt_in_brk_gemeente"
    ),
    RenamedRelation(
        table_name="gebieden_buurten",
        old_column="ligt_in_ggpgebied",
        new_column="ligt_in_gebieden_ggpgebied",
        old_relation_table="rel_gbd_brt_gbd_ggp_ligt_in_ggpgebied",
        new_relation_table="rel_gbd_brt_gbd_ggp_ligt_in_gebieden_ggpgebied"
    ),
    RenamedRelation(
        table_name="gebieden_buurten",
        old_column="ligt_in_ggwgebied",
        new_column="ligt_in_gebieden_ggwgebied",
        old_relation_table="rel_gbd_brt_gbd_ggw_ligt_in_ggwgebied",
        new_relation_table="rel_gbd_brt_gbd_ggw_ligt_in_gebieden_ggwgebied"
    ),
    RenamedRelation(
        table_name="gebieden_buurten",
        old_column="ligt_in_wijk",
        new_column="ligt_in_gebieden_wijk",
        old_relation_table="rel_gbd_brt_gbd_wijk_ligt_in_wijk",
        new_relation_table="rel_gbd_brt_gbd_wijk_ligt_in_gebieden_wijk"
    )
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gebieden_buurten', sa.Column('datum_actueel_tot', sa.DateTime(), autoincrement=False, nullable=True))

    upgrade_relations(op, renamed_relations)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gebieden_buurten', 'datum_actueel_tot')

    downgrade_relations(op, renamed_relations)
    # ### end Alembic commands ###
