"""Remove wijzigingsdatum from KOT model

Revision ID: a18d9a740c07
Revises: 59fa94daa1ea
Create Date: 2019-09-18 09:14:00.799074

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a18d9a740c07'
down_revision = '59fa94daa1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brk_kadastraleobjecten', 'wijzigingsdatum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brk_kadastraleobjecten', sa.Column('wijzigingsdatum', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
