"""muurvlak coordinaten type integer

Revision ID: a7a44cb317a7
Revises: 8823a4593322
Create Date: 2023-04-04 14:16:38.576043

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a7a44cb317a7'
down_revision = '8823a4593322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS legacy.meetbouten_meetbouten")
    op.alter_column('meetbouten_meetbouten', 'x_coordinaat_muurvlak',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('meetbouten_meetbouten', 'y_coordinaat_muurvlak',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.execute("DROP VIEW IF EXISTS legacy.meetbouten_referentiepunten")
    op.alter_column('meetbouten_referentiepunten', 'x_coordinaat_muurvlak',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('meetbouten_referentiepunten', 'y_coordinaat_muurvlak',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.execute("DROP VIEW IF EXISTS legacy.nap_peilmerken")
    op.alter_column('nap_peilmerken', 'x_coordinaat_muurvlak',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('nap_peilmerken', 'y_coordinaat_muurvlak',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS legacy.nap_peilmerken")
    op.alter_column('nap_peilmerken', 'y_coordinaat_muurvlak',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('nap_peilmerken', 'x_coordinaat_muurvlak',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               autoincrement=False)
    op.execute("DROP VIEW IF EXISTS legacy.meetbouten_referentiepunten")
    op.alter_column('meetbouten_referentiepunten', 'y_coordinaat_muurvlak',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('meetbouten_referentiepunten', 'x_coordinaat_muurvlak',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               autoincrement=False)
    op.execute("DROP VIEW IF EXISTS legacy.meetbouten_meetbouten")
    op.alter_column('meetbouten_meetbouten', 'y_coordinaat_muurvlak',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('meetbouten_meetbouten', 'x_coordinaat_muurvlak',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###
