"""Clear wrongly imported relations

Revision ID: b83e1c7228db
Revises: bc1071e546f3
Create Date: 2020-03-31 13:03:23.401391

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

from gobcore.model import GOBModel
from gobcore.model.relations import get_relations

# revision identifiers, used by Alembic.
revision = 'b83e1c7228db'
down_revision = 'bc1071e546f3'
branch_labels = None
depends_on = None


def wrap_query(query: str):
    return sa.text(query) if sa.__version__[0] == "2" else query


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    model = GOBModel()

    connection = op.get_bind()

    for relation_name, relation in get_relations(model)['collections'].items():
        table_name = f"rel_{relation_name}"

        try:
            # The code uses the current GOBModel
            # This model is normally more recent that the database
            # because of the migrations that have still to be processes after this migration
            # So do not fail on any missing tables
            res = connection.execute(wrap_query(f"SELECT * FROM {table_name} WHERE bronwaarde IS NULL LIMIT 1"))

            if res.fetchall():
                print(f"{table_name} contains NULL values for bronwaarde. Clearing table and events.")

                op.execute(wrap_query(f"DELETE FROM events WHERE entity='{relation_name}'"))
                op.execute(wrap_query(f"TRUNCATE {table_name}"))
        except Exception:
            connection.execute(wrap_query("ROLLBACK"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
