"""migrate_ligt_in_ggwpgebied

Revision ID: c8eb0d9596a7
Revises: 0ef7b437e56e
Create Date: 2021-11-16 14:20:07.584078

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c8eb0d9596a7'
down_revision = '0ef7b437e56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # rename old tables back to (old) model version 0.1
    op.rename_table("rel_gbd_brt_gbd_ggp_ligt_in_ggpgebied", "rel_gbd_brt_gbd_ggp__ligt_in_ggpgebied")
    op.rename_table("rel_gbd_brt_gbd_ggw_ligt_in_ggwgebied", "rel_gbd_brt_gbd_ggw__ligt_in_ggwgebied")
    op.rename_table("rel_gbd_wijk_gbd_ggw_ligt_in_ggwgebied", "rel_gbd_wijk_gbd_ggw__ligt_in_ggwgebied")

    # create new model version 0.2 tables
    op.create_table('rel_gbd_brt_gbd_ggp_ligt_in_ggpgebied',
        sa.Column('id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('src_source', sa.String(), autoincrement=False, nullable=True),
        sa.Column('src_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('src_volgnummer', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('bronwaarde', sa.String(), autoincrement=False, nullable=True),
        sa.Column('derivation', sa.String(), autoincrement=False, nullable=True),
        sa.Column('dst_source', sa.String(), autoincrement=False, nullable=True),
        sa.Column('dst_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('dst_volgnummer', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('begin_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('eind_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_last_src_event', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('_last_dst_event', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('_source', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_application', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_source_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_last_event', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('_hash', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_version', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_date_created', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_date_confirmed', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_date_modified', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_date_deleted', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_expiration_date', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_tid', sa.String(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['dst_id', 'dst_volgnummer'], ['gebieden_ggpgebieden._id', 'gebieden_ggpgebieden.volgnummer'], name='rel_gbd_brt_gbd_ggp_ligt_in_ggpgebied_dfk'),
        sa.ForeignKeyConstraint(['src_id', 'src_volgnummer'], ['gebieden_buurten._id', 'gebieden_buurten.volgnummer'], name='rel_gbd_brt_gbd_ggp_ligt_in_ggpgebied_sfk'),
        sa.PrimaryKeyConstraint('_gobid'),
        sa.UniqueConstraint('_source_id', name='rel_gbd_brt_gbd_ggp_ligt_in_ggpgebied_uniq'),
        sa.UniqueConstraint('_tid', name='rel_gbd_brt_gbd_ggp_ligt_in_ggpgebied__tid_key')
    )
    op.create_table('rel_gbd_brt_gbd_ggw_ligt_in_ggwgebied',
        sa.Column('id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('src_source', sa.String(), autoincrement=False, nullable=True),
        sa.Column('src_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('src_volgnummer', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('bronwaarde', sa.String(), autoincrement=False, nullable=True),
        sa.Column('derivation', sa.String(), autoincrement=False, nullable=True),
        sa.Column('dst_source', sa.String(), autoincrement=False, nullable=True),
        sa.Column('dst_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('dst_volgnummer', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('begin_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('eind_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_last_src_event', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('_last_dst_event', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('_source', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_application', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_source_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_last_event', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('_hash', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_version', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_date_created', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_date_confirmed', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_date_modified', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_date_deleted', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_expiration_date', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_tid', sa.String(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['dst_id', 'dst_volgnummer'], ['gebieden_ggwgebieden._id', 'gebieden_ggwgebieden.volgnummer'], name='rel_gbd_brt_gbd_ggw_ligt_in_ggwgebied_dfk'),
        sa.ForeignKeyConstraint(['src_id', 'src_volgnummer'], ['gebieden_buurten._id', 'gebieden_buurten.volgnummer'], name='rel_gbd_brt_gbd_ggw_ligt_in_ggwgebied_sfk'),
        sa.PrimaryKeyConstraint('_gobid'),
        sa.UniqueConstraint('_source_id', name='rel_gbd_brt_gbd_ggw_ligt_in_ggwgebied_uniq'),
        sa.UniqueConstraint('_tid', name='rel_gbd_brt_gbd_ggw_ligt_in_ggwgebied__tid_key')
    )
    op.create_table('rel_gbd_wijk_gbd_ggw_ligt_in_ggwgebied',
        sa.Column('id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('src_source', sa.String(), autoincrement=False, nullable=True),
        sa.Column('src_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('src_volgnummer', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('bronwaarde', sa.String(), autoincrement=False, nullable=True),
        sa.Column('derivation', sa.String(), autoincrement=False, nullable=True),
        sa.Column('dst_source', sa.String(), autoincrement=False, nullable=True),
        sa.Column('dst_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('dst_volgnummer', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('begin_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('eind_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_last_src_event', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('_last_dst_event', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('_source', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_application', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_source_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_last_event', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('_hash', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_version', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_date_created', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_date_confirmed', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_date_modified', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_date_deleted', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_expiration_date', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('_tid', sa.String(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['dst_id', 'dst_volgnummer'], ['gebieden_ggwgebieden._id', 'gebieden_ggwgebieden.volgnummer'], name='rel_gbd_wijk_gbd_ggw_ligt_in_ggwgebied_dfk'),
        sa.ForeignKeyConstraint(['src_id', 'src_volgnummer'], ['gebieden_wijken._id', 'gebieden_wijken.volgnummer'], name='rel_gbd_wijk_gbd_ggw_ligt_in_ggwgebied_sfk'),
        sa.PrimaryKeyConstraint('_gobid'),
        sa.UniqueConstraint('_source_id', name='rel_gbd_wijk_gbd_ggw_ligt_in_ggwgebied_uniq'),
        sa.UniqueConstraint('_tid', name='rel_gbd_wijk_gbd_ggw_ligt_in_ggwgebied__tid_key')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS rel_gbd_brt_gbd_ggp_ligt_in_ggpgebied CASCADE')
    op.execute('DROP TABLE IF EXISTS rel_gbd_brt_gbd_ggw_ligt_in_ggwgebied CASCADE')
    op.execute('DROP TABLE IF EXISTS rel_gbd_wijk_gbd_ggw_ligt_in_ggwgebied CASCADE')

    op.rename_table("rel_gbd_brt_gbd_ggp__ligt_in_ggpgebied", "rel_gbd_brt_gbd_ggp_ligt_in_ggpgebied")
    op.rename_table("rel_gbd_brt_gbd_ggw__ligt_in_ggwgebied", "rel_gbd_brt_gbd_ggw_ligt_in_ggwgebied")
    op.rename_table("rel_gbd_wijk_gbd_ggw__ligt_in_ggwgebied", "rel_gbd_wijk_gbd_ggw_ligt_in_ggwgebied")

    # ### end Alembic commands ###
