"""application

Revision ID: c9d159436795
Revises: f890e0ffd9bd
Create Date: 2018-12-07 08:15:06.708762

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c9d159436795'
down_revision = 'f890e0ffd9bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('application', sa.String(), autoincrement=False, nullable=True))
    op.add_column('gebieden_bouwblokken', sa.Column('_application', sa.String(), autoincrement=False, nullable=True))
    op.add_column('gebieden_buurten', sa.Column('_application', sa.String(), autoincrement=False, nullable=True))
    op.add_column('gebieden_stadsdelen', sa.Column('_application', sa.String(), autoincrement=False, nullable=True))
    op.add_column('gebieden_wijken', sa.Column('_application', sa.String(), autoincrement=False, nullable=True))
    op.add_column('meetbouten_meetbouten', sa.Column('_application', sa.String(), autoincrement=False, nullable=True))
    op.add_column('meetbouten_metingen', sa.Column('_application', sa.String(), autoincrement=False, nullable=True))
    op.add_column('meetbouten_referentiepunten', sa.Column('_application', sa.String(), autoincrement=False, nullable=True))
    op.add_column('meetbouten_rollagen', sa.Column('_application', sa.String(), autoincrement=False, nullable=True))
    op.add_column('nap_peilmerken', sa.Column('_application', sa.String(), autoincrement=False, nullable=True))
    op.add_column('test_catalogue_test_entity', sa.Column('_application', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_catalogue_test_entity', '_application')
    op.drop_column('nap_peilmerken', '_application')
    op.drop_column('meetbouten_rollagen', '_application')
    op.drop_column('meetbouten_referentiepunten', '_application')
    op.drop_column('meetbouten_metingen', '_application')
    op.drop_column('meetbouten_meetbouten', '_application')
    op.drop_column('gebieden_wijken', '_application')
    op.drop_column('gebieden_stadsdelen', '_application')
    op.drop_column('gebieden_buurten', '_application')
    op.drop_column('gebieden_bouwblokken', '_application')
    op.drop_column('events', 'application')
    # ### end Alembic commands ###
