"""Add eind_geldigheid to woz object/deelobject

Revision ID: d26066aaa104
Revises: 7bdd4943e00a
Create Date: 2020-12-08 13:15:30.242318

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd26066aaa104'
down_revision = '7bdd4943e00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('woz_wozdeelobjecten', sa.Column('eind_geldigheid', sa.Date(), autoincrement=False, nullable=True))
    op.add_column('woz_wozobjecten', sa.Column('eind_geldigheid', sa.Date(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('woz_wozobjecten', 'eind_geldigheid')
    op.drop_column('woz_wozdeelobjecten', 'eind_geldigheid')
    # ### end Alembic commands ###
