"""add_heeft_persoonsverblijfplaatsen

Revision ID: d43bcf4d0313
Revises: 594d0ab552fb
Create Date: 2021-07-07 13:08:49.572091

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd43bcf4d0313'
down_revision = '594d0ab552fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rel_brp_prs_brp_pvb_heeft_persoonsverblijfplaatsen',
    sa.Column('id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('src_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('src_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('src_volgnummer', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('bronwaarde', sa.String(), autoincrement=False, nullable=True),
    sa.Column('derivation', sa.String(), autoincrement=False, nullable=True),
    sa.Column('dst_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('dst_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('dst_volgnummer', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_last_src_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_last_dst_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_tid', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dst_id'], ['brp_persoonsverblijfplaatsen._id'], name='rel_brp_prs_brp_pvb_heeft_persoonsverblijfplaatsen_dfk'),
    sa.ForeignKeyConstraint(['src_id'], ['brp_personen._id'], name='rel_brp_prs_brp_pvb_heeft_persoonsverblijfplaatsen_sfk'),
    sa.PrimaryKeyConstraint('_gobid'),
    sa.UniqueConstraint('_source_id', name='rel_brp_prs_brp_pvb_heeft_persoonsverblijfplaatsen_uniq'),
    sa.UniqueConstraint('_tid', name='rel_brp_prs_brp_pvb_heeft_persoonsverblijfplaatsen__tid_key')
    )
    op.create_table('rel_brp_vbl_brp_pvb_heeft_persoonsverblijfplaatsen',
    sa.Column('id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('src_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('src_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('src_volgnummer', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('bronwaarde', sa.String(), autoincrement=False, nullable=True),
    sa.Column('derivation', sa.String(), autoincrement=False, nullable=True),
    sa.Column('dst_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('dst_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('dst_volgnummer', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_last_src_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_last_dst_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_tid', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dst_id'], ['brp_persoonsverblijfplaatsen._id'], name='rel_brp_vbl_brp_pvb_heeft_persoonsverblijfplaatsen_dfk'),
    sa.ForeignKeyConstraint(['src_id'], ['brp_verblijfplaatsen._id'], name='rel_brp_vbl_brp_pvb_heeft_persoonsverblijfplaatsen_sfk'),
    sa.PrimaryKeyConstraint('_gobid'),
    sa.UniqueConstraint('_source_id', name='rel_brp_vbl_brp_pvb_heeft_persoonsverblijfplaatsen_uniq'),
    sa.UniqueConstraint('_tid', name='rel_brp_vbl_brp_pvb_heeft_persoonsverblijfplaatsen__tid_key')
    )
    op.drop_table('rel_brp_pvb_brp_prs_van_persoon')
    op.drop_table('rel_brp_prs_brp_vbl_heeft_verblijfplaatsen')
    op.drop_table('rel_brp_pvb_brp_vbl_met_verblijfplaats')
    op.add_column('brp_personen', sa.Column('heeft_persoonsverblijfplaatsen', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('brp_personen', 'identificatie',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=True,
                    postgresql_using='identificatie::text')
    op.drop_column('brp_personen', 'heeft_verblijfplaatsen')
    op.alter_column('brp_persoonsverblijfplaatsen', 'met_verblijfplaats',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.String(),
                    existing_nullable=True,
                    postgresql_using='met_verblijfplaats::text')
    op.alter_column('brp_persoonsverblijfplaatsen', 'van_persoon',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.String(),
                    existing_nullable=True,
                    postgresql_using='van_persoon::text')
    op.add_column('brp_verblijfplaatsen', sa.Column('heeft_persoonsverblijfplaatsen', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brp_verblijfplaatsen', 'heeft_persoonsverblijfplaatsen')
    op.alter_column('brp_persoonsverblijfplaatsen', 'van_persoon',
                    existing_type=sa.String(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True,
                    postgresql_using='van_persoon::jsonb'
                    )
    op.alter_column('brp_persoonsverblijfplaatsen', 'met_verblijfplaats',
                    existing_type=sa.String(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True,
                    postgresql_using='met_verblijfplaats::jsonb'
                    )
    op.add_column('brp_personen',
                  sa.Column('heeft_verblijfplaatsen', postgresql.JSONB(astext_type=sa.Text()),
                            nullable=True))
    op.alter_column('brp_personen', 'identificatie',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True,
                    postgresql_using='identificatie::text'
                    )
    op.drop_column('brp_personen', 'heeft_persoonsverblijfplaatsen')
    op.create_table('rel_brp_pvb_brp_vbl_met_verblijfplaats',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bronwaarde', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('derivation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_last_src_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_last_dst_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_gobid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_tid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dst_id'], ['brp_verblijfplaatsen._id'], name='rel_brp_pvb_brp_vbl_met_verblijfplaats_dfk'),
    sa.ForeignKeyConstraint(['src_id'], ['brp_persoonsverblijfplaatsen._id'], name='rel_brp_pvb_brp_vbl_met_verblijfplaats_sfk'),
    sa.PrimaryKeyConstraint('_gobid', name='rel_brp_pvb_brp_vbl_met_verblijfplaats_pkey'),
    sa.UniqueConstraint('_source_id', name='rel_brp_pvb_brp_vbl_met_verblijfplaats_uniq'),
    sa.UniqueConstraint('_tid', name='rel_brp_pvb_brp_vbl_met_verblijfplaats__tid_key')
    )
    op.create_table('rel_brp_prs_brp_vbl_heeft_verblijfplaatsen',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bronwaarde', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('derivation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_last_src_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_last_dst_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_gobid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_tid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dst_id'], ['brp_verblijfplaatsen._id'], name='rel_brp_prs_brp_vbl_heeft_verblijfplaatsen_dfk'),
    sa.ForeignKeyConstraint(['src_id'], ['brp_personen._id'], name='rel_brp_prs_brp_vbl_heeft_verblijfplaatsen_sfk'),
    sa.PrimaryKeyConstraint('_gobid', name='rel_brp_prs_brp_vbl_heeft_verblijfplaatsen_pkey'),
    sa.UniqueConstraint('_source_id', name='rel_brp_prs_brp_vbl_heeft_verblijfplaatsen_uniq'),
    sa.UniqueConstraint('_tid', name='rel_brp_prs_brp_vbl_heeft_verblijfplaatsen__tid_key')
    )
    op.create_table('rel_brp_pvb_brp_prs_van_persoon',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src_volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bronwaarde', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('derivation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dst_volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_last_src_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_last_dst_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_gobid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_tid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dst_id'], ['brp_personen._id'], name='rel_brp_pvb_brp_prs_van_persoon_dfk'),
    sa.ForeignKeyConstraint(['src_id'], ['brp_persoonsverblijfplaatsen._id'], name='rel_brp_pvb_brp_prs_van_persoon_sfk'),
    sa.PrimaryKeyConstraint('_gobid', name='rel_brp_pvb_brp_prs_van_persoon_pkey'),
    sa.UniqueConstraint('_source_id', name='rel_brp_pvb_brp_prs_van_persoon_uniq'),
    sa.UniqueConstraint('_tid', name='rel_brp_pvb_brp_prs_van_persoon__tid_key')
    )
    op.drop_table('rel_brp_vbl_brp_pvb_heeft_persoonsverblijfplaatsen')
    op.drop_table('rel_brp_prs_brp_pvb_heeft_persoonsverblijfplaatsen')
    # ### end Alembic commands ###
