"""Add cbs_code

Revision ID: d721110eb79c
Revises: c9d159436795
Create Date: 2019-01-02 12:53:34.719328

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd721110eb79c'
down_revision = 'c9d159436795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gebieden_bouwblokken_geometrie', table_name='gebieden_bouwblokken')
    op.add_column('gebieden_buurten', sa.Column('cbs_code', sa.String(), autoincrement=False, nullable=True))
    op.drop_index('idx_gebieden_buurten_geometrie', table_name='gebieden_buurten')
    op.drop_index('idx_gebieden_stadsdelen_geometrie', table_name='gebieden_stadsdelen')
    op.add_column('gebieden_wijken', sa.Column('cbs_code', sa.String(), autoincrement=False, nullable=True))
    op.drop_index('idx_gebieden_wijken_geometrie', table_name='gebieden_wijken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_gebieden_wijken_geometrie', 'gebieden_wijken', ['geometrie'], unique=False)
    op.drop_column('gebieden_wijken', 'cbs_code')
    op.create_index('idx_gebieden_stadsdelen_geometrie', 'gebieden_stadsdelen', ['geometrie'], unique=False)
    op.create_index('idx_gebieden_buurten_geometrie', 'gebieden_buurten', ['geometrie'], unique=False)
    op.drop_column('gebieden_buurten', 'cbs_code')
    op.create_index('idx_gebieden_bouwblokken_geometrie', 'gebieden_bouwblokken', ['geometrie'], unique=False)
    # ### end Alembic commands ###
