"""Add cbs_code

Revision ID: d721110eb79c
Revises: c9d159436795
Create Date: 2019-01-02 12:53:34.719328

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd721110eb79c'
down_revision = 'c9d159436795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gebieden_buurten', sa.Column('cbs_code', sa.String(), autoincrement=False, nullable=True))
    op.add_column('gebieden_wijken', sa.Column('cbs_code', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gebieden_wijken', 'cbs_code')
    op.drop_column('gebieden_buurten', 'cbs_code')
    # ### end Alembic commands ###
