"""source gebieden ggwgebieden from amsterdam schema

Revision ID: e609c3471ce9
Revises: 3803c9d97842
Create Date: 2022-08-15 09:39:51.241437

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

from gobupload.alembic_utils import RenamedRelation, upgrade_relations, downgrade_relations

# revision identifiers, used by Alembic.
revision = 'e609c3471ce9'
down_revision = '3803c9d97842'
branch_labels = None
depends_on = None

renamed_relations = [
    RenamedRelation(
        table_name="gebieden_ggwgebieden",
        old_column="ligt_in_gemeente",
        new_column="ligt_in_brk_gemeente",
        old_relation_table="rel_gbd_ggw_brk_gme_ligt_in_gemeente",
        new_relation_table="rel_gbd_ggw_brk_gme_ligt_in_brk_gemeente"
    ),
    RenamedRelation(
        table_name="gebieden_ggwgebieden",
        old_column="bestaat_uit_buurten",
        new_column="bestaat_uit_gebieden_buurten",
        old_relation_table="rel_gbd_ggw_gbd_brt_bestaat_uit_buurten",
        new_relation_table="rel_gbd_ggw_gbd_brt_bestaat_uit_gebieden_buurten"
    ),
    RenamedRelation(
        table_name="gebieden_ggwgebieden",
        old_column="ligt_in_stadsdeel",
        new_column="ligt_in_gebieden_stadsdeel",
        old_relation_table="rel_gbd_ggw_gbd_sdl_ligt_in_stadsdeel",
        new_relation_table="rel_gbd_ggw_gbd_sdl_ligt_in_gebieden_stadsdeel"
    )
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gebieden_ggwgebieden', sa.Column('datum_actueel_tot', sa.DateTime(), autoincrement=False, nullable=True))

    upgrade_relations(op, renamed_relations)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gebieden_ggwgebieden', 'datum_actueel_tot')

    downgrade_relations(op, renamed_relations)
    # ### end Alembic commands ###
