"""update decimals

Revision ID: eacbe4d3fa68
Revises: 427f22a6416a
Create Date: 2023-04-20 11:20:55.910321

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

from gobcore.model import GOBModel
from gobcore.typesystem import get_gob_type


# revision identifiers, used by Alembic.
revision = 'eacbe4d3fa68'
down_revision = '427f22a6416a'
branch_labels = None
depends_on = None

model = GOBModel()

def _get_decimals_to_update():
    decimals = []
    for catalog_name, catalog in model.items():
        for collection_name, collection in catalog['collections'].items():
            for attr_name, attr in collection['attributes'].items():
                if attr['type'] == 'GOB.Decimal':
                    decimals.append((catalog_name, collection_name, attr_name, attr))
    return decimals


def upgrade():
    # This migration updates all existing Decimal columns with the correct scale and precision
    decimals_to_update = _get_decimals_to_update()
    connection = op.get_bind()

    for catalog_name, collection_name, attr_name, attr in decimals_to_update:
        tablename = model.get_table_name(catalog_name, collection_name)

        res = connection.execute(f"SELECT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename  = '{tablename}');")

        if not next(res)[0]:
            # Skip, because table does not exist
            continue

        if 'precision' in attr:
            op.alter_column(tablename, attr_name, type_=sa.DECIMAL(precision=10, scale=attr['precision']))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
