"""bag onderzoeken

Revision ID: ef163693f8c3
Revises: 87f428c8951c
Create Date: 2020-05-05 11:44:21.124478

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef163693f8c3'
down_revision = '87f428c8951c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new tables
    op.create_table('bag_onderzoeken',
    sa.Column('volgnummer', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('registratiedatum', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('identificatie', sa.String(), autoincrement=False, nullable=True),
    sa.Column('object_identificatie', sa.String(), autoincrement=False, nullable=True),
    sa.Column('objecttype', sa.String(), autoincrement=False, nullable=True),
    sa.Column('kenmerk', sa.String(), autoincrement=False, nullable=True),
    sa.Column('in_onderzoek', sa.String(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('documentdatum', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('documentnummer', sa.String(), autoincrement=False, nullable=True),
    sa.Column('tijdstip_registratie', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('eind_registratie', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_gobid'),
    sa.UniqueConstraint('_id', 'volgnummer', name='bag_onderzoeken__id_volgnummer_key')
    )
    op.create_table('qa_bag_onderzoeken',
    sa.Column('meldingnummer', sa.String(), autoincrement=False, nullable=True),
    sa.Column('code', sa.String(), autoincrement=False, nullable=True),
    sa.Column('proces', sa.String(), autoincrement=False, nullable=True),
    sa.Column('attribuut', sa.String(), autoincrement=False, nullable=True),
    sa.Column('identificatie', sa.String(), autoincrement=False, nullable=True),
    sa.Column('volgnummer', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('betwijfelde_waarde', sa.String(), autoincrement=False, nullable=True),
    sa.Column('onderbouwing', sa.String(), autoincrement=False, nullable=True),
    sa.Column('voorgestelde_waarde', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.String(), autoincrement=False, nullable=True),
    sa.Column('_date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('_gobid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.String(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_gobid'),
    sa.UniqueConstraint('_id', name='qa_bag_onderzoeken__id_key')
    )
    # Drop old tables
    op.drop_table('bag_onderzoek')
    op.drop_table('qa_bag_onderzoek')
    # Clear events
    op.execute("DELETE FROM events where catalogue = 'bag' and entity = 'onderzoek'")
    op.execute("DELETE FROM events where catalogue = 'qa' and entity = 'bag_onderzoek'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bag_onderzoek',
    sa.Column('volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('registratiedatum', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('identificatie', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('object_identificatie', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('objecttype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kenmerk', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('in_onderzoek', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('documentdatum', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('documentnummer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tijdstip_registratie', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('eind_registratie', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_gobid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_gobid', name='bag_onderzoek_pkey'),
    sa.UniqueConstraint('_id', 'volgnummer', name='bag_onderzoek__id_volgnummer_key')
    )
    op.create_table('qa_bag_onderzoek',
    sa.Column('meldingnummer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('proces', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attribuut', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('identificatie', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('volgnummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('betwijfelde_waarde', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('onderbouwing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('voorgestelde_waarde', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_application', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_source_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_last_event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_confirmed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_gobid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('begin_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('eind_geldigheid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_gobid', name='qa_bag_onderzoek_pkey'),
    sa.UniqueConstraint('_id', name='qa_bag_onderzoek__id_key')
    )
    op.drop_table('qa_bag_onderzoeken')
    op.drop_table('bag_onderzoeken')
    # ### end Alembic commands ###
