FROM amsterdam/python:3.7-buster
MAINTAINER datapunt@amsterdam.nl

# Install gobupload in /app folder
WORKDIR /app

RUN apt-get update && apt-get -y --no-install-recommends install unixodbc-dev

# Install required Python packages
COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt
RUN rm requirements.txt
RUN rm -rf /app/src/gobcore/tests

# Copy gobupload module
COPY gobupload gobupload

# Copy test module
COPY tests tests

# Copy tests
COPY test.sh .flake8 ./

# Copy jenkins files
COPY .jenkins /.jenkins
